// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8b_Fv4YU2WMLwa3Vh801InT7RZkO2wIc',
    appId: '1:82073468410:web:f87f0018105dcd8fd47843',
    messagingSenderId: '82073468410',
    projectId: 'eduspotify-b41f6',
    authDomain: 'eduspotify-b41f6.firebaseapp.com',
    storageBucket: 'eduspotify-b41f6.firebasestorage.app',
    measurementId: 'G-2VSMT0ZMMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJTRbBMi6aKaJMK_3rwSx3zBmuW_xOaM',
    appId: '1:82073468410:android:b93b39eee0791c3bd47843',
    messagingSenderId: '82073468410',
    projectId: 'eduspotify-b41f6',
    storageBucket: 'eduspotify-b41f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPeT2PstrbaaNBhnUCWFz1X3WJoB_ir4',
    appId: '1:82073468410:ios:8483aeacf8260a19d47843',
    messagingSenderId: '82073468410',
    projectId: 'eduspotify-b41f6',
    storageBucket: 'eduspotify-b41f6.firebasestorage.app',
    iosBundleId: 'com.example.pruebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPeT2PstrbaaNBhnUCWFz1X3WJoB_ir4',
    appId: '1:82073468410:ios:8483aeacf8260a19d47843',
    messagingSenderId: '82073468410',
    projectId: 'eduspotify-b41f6',
    storageBucket: 'eduspotify-b41f6.firebasestorage.app',
    iosBundleId: 'com.example.pruebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8b_Fv4YU2WMLwa3Vh801InT7RZkO2wIc',
    appId: '1:82073468410:web:17a8debdf7d7be34d47843',
    messagingSenderId: '82073468410',
    projectId: 'eduspotify-b41f6',
    authDomain: 'eduspotify-b41f6.firebaseapp.com',
    storageBucket: 'eduspotify-b41f6.firebasestorage.app',
    measurementId: 'G-S71HJTEK5P',
  );
}
