// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpX4A61ne77k54w_Y1QvTIIodHBZZ424',
    appId: '1:768837262110:web:c93ecbc2b5e4c263f3470f',
    messagingSenderId: '768837262110',
    projectId: 'nexo-bcb44',
    authDomain: 'nexo-bcb44.firebaseapp.com',
    storageBucket: 'nexo-bcb44.firebasestorage.app',
    measurementId: 'G-C7RPYJHSGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwatZGT8caLkcMFm27RCi9tyA6GcFxYyI',
    appId: '1:768837262110:android:88fd3c7f9e771593f3470f',
    messagingSenderId: '768837262110',
    projectId: 'nexo-bcb44',
    storageBucket: 'nexo-bcb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4NR1GraSCpnuVGI557kizS1pKx9h8ebo',
    appId: '1:768837262110:ios:556cbbeb44493f7ef3470f',
    messagingSenderId: '768837262110',
    projectId: 'nexo-bcb44',
    storageBucket: 'nexo-bcb44.firebasestorage.app',
    iosBundleId: 'com.example.pruebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4NR1GraSCpnuVGI557kizS1pKx9h8ebo',
    appId: '1:768837262110:ios:556cbbeb44493f7ef3470f',
    messagingSenderId: '768837262110',
    projectId: 'nexo-bcb44',
    storageBucket: 'nexo-bcb44.firebasestorage.app',
    iosBundleId: 'com.example.pruebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHpX4A61ne77k54w_Y1QvTIIodHBZZ424',
    appId: '1:768837262110:web:307f41c1e2a15aa1f3470f',
    messagingSenderId: '768837262110',
    projectId: 'nexo-bcb44',
    authDomain: 'nexo-bcb44.firebaseapp.com',
    storageBucket: 'nexo-bcb44.firebasestorage.app',
    measurementId: 'G-7GKKY2N034',
  );

}